### ISSUE TITLE
INI Request: rusEFI 2020.07.06.mre_f4.2108843221

### ISSUE THREAD

**Issue by Abricosvw** [nearwood/msqur#54]
![Screenshot_20200707-102814](https://user-images.githubusercontent.com/35018246/86796446-96df2a80-c03c-11ea-8edb-0a3b42fc57e6.jpg)

**Comment by nearwood** [comment]
This is for rusEFI's fork of this project: https://github.com/rusefi/msqur

Please file your request there.
